# Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  version: 5.0.2
  agentVersion: 3.0.0
  cpuset: true
  automaticOrphanedNodeCleanup: true
  sysctls:
    - "fs.aio-max-nr=2097152"
  network:
    hostNetworking: true
  datacenter:
    name: us-central1
    racks:
      - name: us-central1-c
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          storageClassName: local-raid-disks
          capacity: 369G
        resources:
          limits:
            cpu: 30
            memory: 199G
          requests:
            cpu: 30
            memory: 199G
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - us-central1-c
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule